### GET request all dishes
GET http://localhost:5000/api/dishes/

### GET request dish by sepcific name
GET http://localhost:5000/api/dishes/Pasulj

### POST request one dish
POST http://localhost:5000/api/dishes
Content-Type: application/json
Cookie: key=first-value

{
  "name" : "Test",
  "ingredients" :  ["1", "2"],
  "preparationSteps" :  ["1", "2"],
  "cookingTime" : 15,
  "origin" : "value",
  "difficulty" : "value"
}

### DELETE request id dish
DELETE http://localhost:5000/api/dishes/ID


### Get request id dish
GET http://localhost:5000/api/dish/67f91575d64990fa46b71243